import Image from "next/image"
import SocialBTNs from "@/components/ui/SocialBTNs"
// TODO add <meta name="darkreader-lock"> to metadata to disable dark reader in specific pages

export const metadata = {
  title : {
    default : "Home",
    template : "%s"
  },
  description : "Generated by create next app"
}

export default async function Home() {
  return (
    <div className=" sm:w-[1300px] max-w-none min-h-screen mt-10 flex flex-col gap-10 prose prose-purple sm:prose-lg sm:prose-code:text-base prose-p:dark:text-[#D9D9D9]  prose-li:dark:text-[#D9D9D9] dark:prose-invert">
      <div className=" justify-center items-center flex flex-col lg:flex-row max-w-none ">
        <div className=" max-w-prose">
          <h1>Welcome to Ed's Corner (EC)</h1>
          <p>My little online space to share valuable thoughts on my interests.</p>
          <p>Everything it's still under work but I just want to share as fast as possible! If something's missing or breaks it's all under control, until it's not anymore...</p>
          <p>Criticism and tips are always embraced.</p>
        </div>
        <div className="min-h-[210px] mt-4 lg:mt-0 min-w-[210px] max-h-[400px] max-w-[400px] overflow-hidden rounded-[30px] relative">
          <Image
            src="/assets/media/imgs/cool_cat.jpg"
            width={400}
            height={400}
            className=" object-cover not-prose w-full h-full ml-6 scale-[1.25] ss:scale-[1.5]"
            // className=" object-cover text-white fill-white lg:h-[300px] lg:w-[300px] scale-[1.5] ml-6 xl:ml-16 mt-12 absolute top-0"
            color="white"
            alt="logo"
            priority={true}
            // quality={100}
            // quality={100}
            // sizes="(max-width: 31px) 100%"
          />
        </div>
      </div>
      <div className="top-4 flex flex-col justify-center items-center mt-20 text-center">
        <h1>Visit the <span><a href="blog">blog</a></span> or Contact me in the meantime</h1>
        <div className="flex prose-p:h-5 gap-16">
          {/* <p>E-mail: z</p> */}
          <div className="flex items-start flex-col gap-3 justify-start text-left">
            <a className=" text-primary_text_color no-underline">Discord: is_ec</a>
            <a href="https://www.skool.com/@leof-dopp-8139">Skool</a>
          </div>
          <SocialBTNs />
        </div>
      </div>
    </div>
  )
}
